version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os}}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc

brews:
  - name: leaseweb-cli
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@nmishin.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/Nmishin/leaseweb-cli"
    description: "The command line interface for Leaseweb API"
    license: "Apache-2.0"
    skip_upload: auto
    extra_install: |
      chmod 0555, bin/"leaseweb-cli"
    repository:
      owner: Nmishin
      name: homebrew-tap
      # see https://goreleaser.com/errors/resource-not-accessible-by-integration
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
